stages:

  stage_01_data_ingestion:
    cmd: python src/Object_Detection/pipeline/data_ingestion.py
    deps:
      - src/Object_Detection/pipeline/data_ingestion.py
      - config/config.yaml
    outs:
      - src/Object_Detection/artifact_dir/data_ingestion

  stage_02_prepare_base_model:
    cmd: python src/Object_Detection/pipeline/prepare_base_model.py
    deps:
      - src/Object_Detection/pipeline/prepare_base_model.py
      - config/config.yaml
    outs:
      - src/Object_Detection/artifact_dir/prepare_base_model
  
  stage_03_requirements_installing:
    cmd: pip install -r src/Object_Detection/artifact_dir/prepare_base_model/base_model/requirements.txt
  
  stage_04_model_training:
    cmd: python src/Object_Detection/artifact_dir/prepare_base_model/base_model/train.py --img 416 --batch 16 --epochs 1 --data 'C:/Users/arun7/Desktop/projects/Computer_Vision/Object_Detection/src/Object_Detection/artifact_dir/data_ingestion/extracted_data/data.yaml' --cfg src/Object_Detection/artifact_dir/prepare_base_model/base_model/models/Custom_Yolov5s.yaml --weights 'yolov5s.pt' --name yolov5s_results  --cache

  stage_05_inferencing:
    cmd: python src/Object_Detection/artifact_dir/prepare_base_model/base_model/detect.py --weights src/Object_Detection/artifact_dir/prepare_base_model/base_model/runs/train/yolov5s_results/weights/best.pt --img 416 --conf 0.5 --source C:/Users/arun7/Desktop/projects/Computer_Vision/Object_Detection/src/Object_Detection/artifact_dir/data_ingestion/ingested_test_data/images
    